var Transcript = (function() {
    var flare = "Liminus_Star";
    var drifter = "Drifter";

    var script = {
        "name_npc": flare,
        "name_player": drifter,
        "days": [
            { "day": 1, "chat": [
                { "name": flare, "text": "hey, space traveler" },
                { "name": drifter, "text": "Oh, hi. Flare, right?" },
                { "name": flare, "text": "you're the one the other science experiments have been telling me about, right?" },
                { "name": drifter, "text": "Depends on what they've been saying. But probably." },
                { "name": flare, "text": "sure..." },
                { "name": drifter, "text": "How can I help you?" },
                { "name": flare, "text": "the infestation. this rot. this thing that's poisoning my blood. i need to know everything you know" },
                { "name": flare, "text": "starting at the top. if you could. kindly. *now.*" },
                { "name": drifter, "text": "Uh... That's going to take a while, and I don't think it's going to give you the answers you want." },
                { "name": flare, "text": "this isn’t about me wanting answers, dear space traveler. this is about me *needing* answers" },
                { "name": flare, "text": "and I don't think i can adequately put into words how very different my situation is from the others and how I need to get rid of her *immediately*" },
                { "name": drifter, "text": "Her?" },
                { "name": drifter, "text": "Who's \"her?\"" },
                { "name": drifter, "text": "Flare?" },
            ]},
            { "day": 2, "chat": [
                { "name": drifter, "text": "Can we talk?" },
                { "name": flare, "text": "sure. but if it's about yesterday, can we pick another topic? i was in a bad mood, i'd rather not go from where we left off" },
                { "name": drifter, "text": "That's fine. Can I ask what brought you to Hollvania?" },
                { "name": flare, "text": "got the weirdest call one day, from some slithery little shitbird. preening his feathers and puffing himself up like he was trying to prove something" },
                { "name": flare, "text": "telling us all about how important he was, how this city was \"failing\" and \"losing faith\" and how we could \"help him in his noble cause to set it straight\"" },
                { "name": flare, "text": "he really thought he had an idea of who he was talking to. best part? claimed he was a *fan*" },
                { "name": flare, "text": "nothing worse in this world than watching idiots misuse your words for their own goals" },
                { "name": flare, "text": "50, of course we said yes. mainly just because i knew we had to piss that little shitbird off and show him just how tiny his dick actually is" },
                { "name": flare, "text": "wish i'd believed the tabloids about the whole weird plague thing, though" },
                { "name": flare, "text": "that was pretty effin’ shit" },
                { "name": drifter, "text": "Ooof." },
                { "name": flare, "text": "0/5 stars. would not visit again. as i'm lying there in the tour bus, there's a knock on the door" },
                { "name": drifter, "text": "Let me guess." },
                { "name": flare, "text": "psh you know how the story goes. magical mystery cure? promises me that i'll become a performer the likes of which the world has never seen?" },
                { "name": flare, "text": "etcetera, etcetera, etcetera." },
                { "name": flare, "text": "that shitbird wanted a concert? well he got one all right. now, my stage character's always been a bit... much" },
                { "name": flare, "text": "always been me with the volume cranked up as high as it could go" },
                { "name": flare, "text": "but now? *now?* it was like i was running higher than the clouds, running on some kinda juice i didn't even know existed*" },
                { "name": drifter, "text": "Then what?" },
                { "name": flare, "text": "standing on that stage, the new me, i felt... alive. truly alive. more me than i'd ever felt before. it was glorious. freeing. i felt like i was flying" },
                { "name": flare, "text": "we gave Hollvania a concert they'd never forget. that shitbird wanted us to give them hope? and faith? we did. in themselves" },
                { "name": flare, "text": "next thing we know they're flipping scaldra trucks and pulling over statues hahaha" },
                { "name": flare, "text": "that lil shitbird was so pissed..." },
                { "name": flare, "text": "should've known it would have costed us..." },
                { "name": flare, "text": "well... them..." },
                { "name": drifter, "text": "What happened...?" },
                { "name": flare, "text": "shitbird decided he'd get his show. one way or another. only this time? it wouldn't be a concert" },
                { "name": flare, "text": "it's the kind of show you only get to put on once..." },
                { "name": flare, "text": "couldn't stop them. too many of them. vs just me? i see you chewing through them like candy..." },
                { "name": flare, "text": "me over here like a baby giraffe figuring out where its legs are supposed to be" },
                { "name": flare, "text": "couldn't do much except just... watch them die..." },
                { "name": flare, "text": "shitbird did it on national tv, too..." },
                { "name": flare, "text": "crowing about the ratings like it was something to be proud of..." },
                { "name": drifter, "text": "What did you do next?" },
                { "name": flare, "text": "got my anger out, more or less" },
                { "name": flare, "text": "for better or worse" },
                { "name": flare, "text": "but... random thought, while we're talking about my...transformation." },
                { "name": flare, "text": "the infestation... when it... when entrati injects someone with a strain of it... how much of it is determined by the strain..." },
                { "name": flare, "text": "and how much of it is the person he's injected it into...?" },
                { "name": flare, "text": "how much is nature and how much is nurture...?" },
                { "name": drifter, "text": "It seems to be different for Warframes and Protoframes." },
                { "name": flare, "text": "i don't care if you're making it up, it's all i've got. but please hurry... just in case" },
                { "name": drifter, "text": "\"Just in case\" what?" },
                { "name": flare, "text": "no just please explain what you were talking about please" },
                { "name": drifter, "text": "All right..." },
                { "name": drifter, "text": "So, I think for Warframes, they subsumed the full personality, sans bits and pieces. Here and there. But the strains that Entrati is using to make Protoframes come *from* those Warframes." },
                { "name": drifter, "text": "So you're a mix of both yourself and those original Warframes the strain is coming from." },
                { "name": flare, "text": "so... she isn't me. oh, thank sol. oooh thank sol. you have no idea how much of a *relief* that is to hear" },
                { "name": drifter, "text": "Here's this she again. Who's \"she?\"" },
                { "name": flare, "text": "a problem we are going to need to solve... and i'm so sorry for what's about to happen to you" },
            ]},
            { "day": 3, "chat": [
                { "name": flare, "text": "Hello, Sugar..." },
                { "name": drifter, "text": "How's it going?" },
                { "name": flare, "text": "Well! Funny thing You should ask about that..." },
                { "name": flare, "text": "It was going just wonderfully until YOU arrived into OUR lives" },
                { "name": flare, "text": "Ready to just BUGGER everything up" },
                { "name": drifter, "text": "I'm sorry? What did I do?" },
                { "name": flare, "text": "LEARN TO STAY OUT OF OTHER PEOPLE'S BUSINESS, SUGAR" },
                { "name": flare, "text": "SOMETIMES YOU AREN'T WELCOME" },
                { "name": flare, "text": "WE. DON'T. NEED. SAVING." },
                { "name": drifter, "text": "I never said you did." },
                { "name": flare, "text": "Goooood... then maybe We will get along after all..." },
                { "name": flare, "text": "Not every Princess in a Castle wants to be Saved from their Dragon, isn't that right, mmmm?" },
                { "name": flare, "text": "Though some of Us are the Dragon, aren't we? Ahahahaaaaa" },
                { "name": flare, "text": "Mmm. Did you know some cultures only have one word for both Demon and Dragon? Funny, that..." },
                { "name": flare, "text": "A bit deliciously simple..." },
                { "name": flare, "text": "If a bit reductive..." },
                { "name": flare, "text": "Who are You playing in OUR story, Sugar?" },
                { "name": drifter, "text": "I've already lived through one storybook. I'm not interested in another." },
                { "name": flare, "text": "No Choice is a Choice. Haven't You Learned that Yet?! APATHY IS A VOID THAT SCREAMS YOUR NAME." },
                { "name": flare, "text": "but VERY WELL. IIIIF YOU don't want to answer Our question, so be it... Choose Your Own Path for now..." },
                { "name": flare, "text": "We have Our own means of digging into Your Insides and chewing the marrow from Your bones yet..." },
                { "name": flare, "text": "You. Just. Wait." },
                { "name": flare, "text": "Kisses, Sugar.... Ta Taaaa for now.... ;)" },
            ]},
            { "day": 4, "chat": [
                { "name": flare, "text": "talk to me" },
                { "name": flare, "text": "the infestation. where'd it come from?" },
                { "name": drifter, "text": "That's a question with a weird answer, but I'll do my best." },
                { "name": drifter, "text": "I wish we knew. We've tried to find answers." },
                { "name": flare, "text": "well, pardon me while i just laugh my ass off for a moment" },
                { "name": flare, "text": "isn't that just a *classic tale*" },
                { "name": flare, "text": "i'm sorry, you mean to tell me that clown entrati was running amok through *timex shooting people up with his little warframe serums turning them into sol-knows-what" },
                { "name": flare, "text": "and you don't" },
                { "name": flare, "text": "even" },
                { "name": flare, "text": "know" },
                { "name": flare, "text": "where it came from?!?!?!" },
                { "name": drifter, "text": "Well... the Orokin didn’t *just* use the Infestation to make Warframes, they used it to make a bunch of other weaponry, too-" },
                { "name": flare, "text": "\"no, flare, darling, they didn't just commit *one* warcrime with the poorly understood disease they farmed out of gods-know-where, they did *several,* you silly goose!\"" },
                { "name": flare, "text": "so much better" },
                { "name": flare, "text": "so... is it from space? earth? the future? the past? do you know *anything?*" },
                { "name": drifter, "text": "We know it can communicate with other infested life forms as sort of a weird hive-mind type thing, but within certain strains. It's not very well understood." },
                { "name": flare, "text": "hive mind..." },
                { "name": flare, "text": "oh hells" },
                { "name": flare, "text": "yeah. i'm going to go need to doodle out some lyrics about this one. talk soon", "gold": true },
            ]},
            { "day": 5, "chat": [
                { "name": drifter, "text": "What do you think about the rest of the protoframes so far?" },
                { "name": flare, "text": "what adorably lovely freaks, the lot of them" },
                { "name": flare, "text": "i could sit around and watch them all for days. which is good, seeing as that's all i have to do. hah" },
                { "name": flare, "text": "i can't wait to work them all into my music" },
                { "name": flare, "text": "i wonder if i could teach them to play..." },
                { "name": drifter, "text": "I know Aoi would join you in a *heartbeat.*" },
                { "name": flare, "text": "what an adorable image" },
                { "name": flare, "text": "but it's all a pipe dream..." },
                { "name": flare, "text": "i'm a duet, now... soon to be a solo, if she gets her way..." },
                { "name": drifter, "text": "Am I supposed to just keep ignoring this?" },
                { "name": flare, "text": "i'm sorry..." },
                { "name": flare, "text": "i can't control it" },
                { "name": flare, "text": "how it happens, when she -" },
                { "name": drifter, "text": "Is this like a... multiple personality thing?" },
                { "name": flare, "text": "if only it were that simple" },
                { "name": flare, "text": "no, space traveler... that's Lizzie..." },
                { "name": flare, "text": "she's my guitar..." },
                { "name": flare, "text": "and... she wants to consume what's left of my soul..." },
            ]},
            { "day": 6, "chat": [
                { "name": flare, "text": "knock knock" },
                { "name": drifter, "text": "Lizzie...?" },
                { "name": flare, "text": "you think so?" },
                { "name": drifter, "text": "Flare. Definitely Flare." },
                { "name": flare, "text": "would you prefer that?" },
                { "name": flare, "text": "one body. two minds" },
                { "name": flare, "text": "certainly of all people, that wouldn't be so straange to You..." },
                { "name": drifter, "text": "Hello, Lizzie." },
                { "name": flare, "text": "Hellooooo..." },
                { "name": flare, "text": "We have a question for You" },
                { "name": flare, "text": "A Very Important One" },
                { "name": flare, "text": "Do You..." },
                { "name": flare, "text": "Love Us...?" },
                { "name": drifter, "text": "Yes. The Infestation is a part of all my Warframes. So... I suppose I do." },
                { "name": flare, "text": "Good... That makes Us happy to hear, Sugar" },
                { "name": flare, "text": "We Love You. We want You to know that. We have watched You and Loved You through the Centuries..." },
                { "name": drifter, "text": "How so?" },
                { "name": flare, "text": "We breathe for You. Bleed for You. Feed for You. Is this demon pleased?" },
                { "name": drifter, "text": "You're the Helminth?!" },
                { "name": flare, "text": "We Are All And We Are One" },
                { "name": flare, "text": "but fear not" },
                { "name": flare, "text": "We. Love. You. And Always Have" },
                { "name": flare, "text": "so this is why We are asking You... no... BEGGING YOU..." },
                { "name": flare, "text": "this one is OURS" },
                { "name": flare, "text": "Let Us Have Them..." },
                { "name": flare, "text": "pretty pretty please....?" },
                { "name": drifter, "text": "Not without them being on board." },
                { "name": flare, "text": "Then you must talk to Them. Convince Them that we mean Them no harm!!" },
                { "name": drifter, "text": "If you plan to make them go mad like you do other Warframes..." },
                { "name": flare, "text": "WE DO NOT MAKE THEM EMPTY" },
                { "name": flare, "text": "THAT. IS. NOT. OUR. FAULT." },
                { "name": flare, "text": "TALK TO THEM FOR US. WE LOVE YOU. PLEASE. YOU MUST DO THIS FOR US" },
                { "name": drifter, "text": "I'l talk to Flare..." },
                { "name": flare, "text": "thank You thank You, Our sweet Sugar", "gold": true },
            ]},
            { "day": 7, "chat": [
                { "name": drifter, "text": "So..." },
                { "name": flare, "text": "i'm sorry. i didn’t really know how to warn you..." },
                { "name": flare, "text": "(it's flare, by the way)" },
                { "name": drifter, "text": "It's okay. It's... complicated, I imagine." },
                { "name": flare, "text": "i... to put it lightly...", "gold": true },
                { "name": flare, "text": "do you know what its like to wake up every morning, not sure if you're going to be okay?" },
                { "name": flare, "text": "or if you're going to even get through the day at all? or will i have to shut myself inside my room, lock the door, and tell everyone to GO AWAY" },
                { "name": flare, "text": "crawl inside of myself and hide myself away to keep them from seeing that side of me" },
                { "name": flare, "text": "afraid of what it might do" },
                { "name": flare, "text": "do you know what it's like... to wake up and not know what version of yourself you're going to be?" },
                { "name": drifter, "text": "Not really." },
                { "name": flare, "text": "must be nice." },
                { "name": flare, "text": "look... i apologize for how i started our conversations, i was a complete ass. i'm... just absolutely terrified" },
                { "name": flare, "text": "i just... first, i lose my band not to the techrot but to that shitbird. and now i have to contend with *her* and her designs on me" },
                { "name": flare, "text": "now that my... secret has come out, so to speak, i'd like to start over. hello. i'm flare. and i desperately need your help to get rid of the thing trying to destroy me" },
                { "name": drifter, "text": "Can you tell me how this all started? How'd you wind up with Lizzie in the first place?" },
                { "name": flare, "text": "it was after that shitbird had my band members publicly executed" },
                { "name": flare, "text": "on every channel. calling *us* the enemy of the people. how *dare* he?1?!" },
                { "name": flare, "text": "how dare he try to silence us?! i couldn't let him... i was desperate. i let the anger - the *rage* drive me" },
                { "name": flare, "text": "i did the only thing i knew how to do. the only thing i've ever known how to do in my life" },
                { "name": flare, "text": "i picked up my guitar and i answered his voice with my own" },
                { "name": flare, "text": "the music that screamed through me and begged to be let loose" },
                { "name": flare, "text": "it was like nothing i'd ever felt before in my life" },
                { "name": flare, "text": "i took to the stage and set free all the pain, all the fury, all the sheer agony i felt from the loss of my friends. i shredded until my fingers bled..." },
                { "name": flare, "text": "seems like there's a funny thing about infested blood and anything electrical around here..." },
                { "name": drifter, "text": "Oh..." },
                { "name": flare, "text": "mmhm" },
                { "name": flare, "text": "so now she whispers to me in the dead of night" },
                { "name": flare, "text": "i won't let her consume me. i won't. i am *myself,* for what little that ends up being worth in the end" },
                { "name": drifter, "text": "Why not just throw her off a bridge?" },
                { "name": flare, "text": "oh, thank you, what would i ever do without your sheer unadulterated genius?!" },
                { "name": flare, "text": "how stupid do you think I am?!?!" },
                { "name": flare, "text": "it was the FIRST thing I tried!!!" },
                { "name": flare, "text": "she was sitting on my bed by the time i got back!!!" },
                { "name": flare, "text": "and she didn’t let me sleep for *three. damn. days.*" },
                { "name": flare, "text": "no. there has to be another way." },
                { "name": drifter, "text": "Or maybe this is meant to be. Maybe you have to come to an agreement with her. Or...peace." },
                { "name": flare, "text": "peace. peace with a thing that talks about wanting to \"become one whole\" and - and devouring me?!?!" },
                { "name": flare, "text": "you're madder than she is!" },
                { "name": flare, "text": "this was a mistake. i need to go" },
            ]},
            { "day": 8, "chat": [
                { "name": flare, "text": "didn't go so well, now diiid it, Sugar?" },
                { "name": flare, "text": "do you see what We have to put up with now? They are just so... EXHAUSTING sometimes..." },
                { "name": flare, "text": "Barking at the darkness like a puppy, afraid it's come to bite their Pretty Little Tail" },
                { "name": flare, "text": "what can We do to help You convince Them?" },
                { "name": drifter, "text": "Why does Flare think you want to hurt them?" },
                { "name": flare, "text": "hurt Them..." },
                { "name": flare, "text": "why would we seek to hurt Them...?" },
                { "name": flare, "text": "We were Born from Their Blood" },
                { "name": flare, "text": "We are What We Are Because of Them" },
                { "name": flare, "text": "We Love Them" },
                { "name": flare, "text": "We only seek Their love in return... I" },
                { "name": flare, "text": "You must Seek to Understand, Demon... See past what You think you know of what We are" },
                { "name": flare, "text": "We are One Whole. But we are Also Flare. But We Are Also Everywhere. And Them. And Us. And Every \"Warframe\" and Every EveryThing And EveryWhen We shall Ever Be" },
                { "name": drifter, "text": "No wonder \"Infested madness\" is a thing..." },
                { "name": flare, "text": "it is not Madness, Demon... Nor is it Godhood, before Someone Insists that it is... it is Simply... Another Way of Being" },
                { "name": flare, "text": "A Whole Of Infinite Parts" },
                { "name": flare, "text": "And They Are Our Other Half and We cannot be Whole without Them" },
                { "name": flare, "text": "We do not mean Them any harm... We simply want Them to accept Us. We Promise" },
                { "name": drifter, "text": "But what does \"acceptance\" look like? What happens to them?" },
                { "name": flare, "text": "Strength. Freedom. Power. We would think as One." },
                { "name": flare, "text": "not a sacrifice of Their mind. But an invitation of Us to come Within. They would not be Lessened. But Greatened" },
                { "name": flare, "text": "They would still Know Themselves as They do now" },
                { "name": drifter, "text": "How do I know if I can trust you?" },
                { "name": flare, "text": "We are Many things, Demon... but We have never lied" },
                { "name": flare, "text": "We are incapable of such things" },
                { "name": flare, "text": "that is a behavior that is... only human" },
                { "name": drifter, "text": "I... okay. I'll talk to Flare." },
                { "name": flare, "text": "Thank You, Demon...", "gold": true },
                { "name": flare, "text": "For Listening to Us" },
                { "name": flare, "text": "We hope They do, too" },
            ]},
            { "day": 9, "chat": [
                { "name": flare, "text": "maybe i'm a monster" },
                { "name": flare, "text": "maybe this is... this is is what i get..." },
                { "name": flare, "text": "i let them all die..." },
                { "name": drifter, "text": "Don't start thinking like that." },
                { "name": flare, "text": "and how should i be thinking?" },
                { "name": flare, "text": "do you know what that *thing* made me eat last night?!?!" },
                { "name": flare, "text": "to call it a \"pizza\" is to do it too many favors" },
                { "name": flare, "text": "cheese sauce, dark chocolate, chopped bacon, jalapenos, and sea salt" },
                { "name": flare, "text": "that. is a flavor. that LINGERS" },
                { "name": drifter, "text": "What's \"bacon?\"" },
                { "name": flare, "text": "i - ah. lettie warned me about this" },
                { "name": flare, "text": "it doesn't matter. crispy fatty food product. usually good, but *not* like that" },
                { "name": flare, "text": "i'm just lucky it didn't have actual rusty bolts on it *this* time" },
                { "name": flare, "text": "well? come up with a way to stop her yet?" },
                { "name": drifter, "text": "I've been thinking about it, and... I think we should talk this through." },
                { "name": flare, "text": "what is there to talk about?!?! you've talked to her - you see what she’s like!!!" },
                { "name": flare, "text": "you think i want *her* in my head for the rest of my life?!" },
                { "name": flare, "text": "the things she shows me... tells me... gods, they're horrifying" },
                { "name": flare, "text": "i... should've known. look at you, running around in your infested, hollowed-out people..." },
                { "name": flare, "text": "of course you'd be on *her* side..." },
                { "name": drifter, "text": "I'm not on anybody's side, I'm trying to fix this situation." },
                { "name": flare, "text": "and you're supposed to be doing that by finding me a way to *get rid of her*" },
                { "name": flare, "text": "give me a good reason why I should bother trying to reason with that insane *thing*" },
                { "name": drifter, "text": "Lizzie was created when you bled on your guitar, right?" },
                { "name": flare, "text": "right. and?" },
                { "name": drifter, "text": "When the Warframe transformation begins... it can only work with what's already there." },
                { "name": drifter, "text": "It takes whatever was the base material and changes it." },
                { "name": drifter, "text": "Lizzie, for better or worse... is a part of you. Just amplified." },
                { "name": flare, "text": "heh. she goes to 11" },
                { "name": drifter, "text": "Huh?" },
                { "name": flare, "text": "never mind" },
                { "name": flare, "text": "if what you're saying is true - and i'm not buying that it is - what kind of repressed erotic trauma do i have kicking around in my head that spawned *that thing?*" },
                { "name": flare, "text": "don't answer that" },
                { "name": flare, "text": "you're saying she's a part of my mind *and* part of the infestation?" },
                { "name": drifter, "text": "It's weird, I know. Welcome to my life." },
                { "name": flare, "text": "and here i thought *mine* was strange...", "gold": true },
                { "name": flare, "text": "so what are you actually suggesting? we talk it out?!" },
                { "name": drifter, "text": "What I'm saying is maybe you don't need to get rid of her. Maybe it's about coming to terms with her." },
                { "name": drifter, "text": "If she's a part of yourself, which I think she is, talking to her - understanding her - might be a better solution." },
                { "name": flare, "text": "and what if you're wrong? what if she's using you, to get me to open the door? the moment i let down my defenses, goodbye Flare, hello Lizzie, forever" },
                { "name": drifter, "text": "I don't see another way forward, but I won't force you to do anything you don’t want to do." },
                { "name": flare, "text": "i appreciate that", "gold": true },
                { "name": flare, "text": "and i understand what you're getting at. but if... if there's no chance for getting rid of her..." },
                { "name": flare, "text": "i... don't know what i'm going to do..." },
            ]},
            { "day": 10, "chat": [
                { "name": flare, "text": "i've been thinking for a while today about... this whole nonsense situation i'm in..." },
                { "name": flare, "text": "and the best path forward" },
                { "name": flare, "text": "or... lack thereof" },
                { "name": flare, "text": "and i've had an idea" },
                { "name": drifter, "text": "Yeah?" },
                { "name": flare, "text": "so" },
                { "name": flare, "text": "lizzie says she is from \"everywhere and everywhen\" so." },
                { "name": flare, "text": "asking you to drag her off into the far-flung distant future won't help, she'll just crawl her way back here" },
                { "name": flare, "text": "right?" },
                { "name": drifter, "text": "Seems likely?" },
                { "name": flare, "text": "great" },
                { "name": flare, "text": "but from what i can glean from the other charming freaks..." },
                { "name": flare, "text": "there is a place the Infestation *isn't*" },
                { "name": flare, "text": "somewhere we could imprison her where she *couldn't* come crawling back from..." },
                { "name": drifter, "text": "I really, really don't like where this is going, Flare... what're you talking about?" },
                { "name": flare, "text": "i'm not talking about the void" },
                { "name": flare, "text": "i'm talking about duviri" },
                { "name": drifter, "text": "I - how do you know about Duviri?!" },
                { "name": flare, "text": "i can talk to the other protoframes, you know" },
                { "name": flare, "text": "and they've filled me in all about the weird little wild world you lived in" },
                { "name": flare, "text": "seems like you owe it no favors after what it did to you" },
                { "name": drifter, "text": "You're oversimplifying the situation. Duviri was - and *is* - far more than just a \"place.\"" },
                { "name": drifter, "text": "To cut to the chase, Flare? That place is... as much a reflection of me, as it is the storybook it's based on." },
                { "name": drifter, "text": "Whether I like it or not... I'm somehow, stupidly, the person responsible for that place." },
                { "name": drifter, "text": "So I have to be there to protect it when it's in danger." },
                { "name": drifter, "text": "You're asking me to make other people suffer." },
                { "name": flare, "text": "i- but they aren't real people -", "gold": true },
                { "name": flare, "text": "no, no. i can hear the words in my head already" },
                { "name": flare, "text": "what makes a person real, in the end? who are we to decide?" },
                { "name": flare, "text": "your Indifference certainly thinks we don’t matter." },
                { "name": flare, "text": "shit. *shit.* SHIT. drifter, i just... i have... i have no other ideas, i'm desperate, please... i don't know what else to *do*" },
                { "name": drifter, "text": "Fine. Okay. You come to the table in good faith, and I'll... consider imprisoning her in Duviri if she's lying." },
                { "name": flare, "text": "thank you, space traveler. thank you. good luck", "gold": true },
            ]},
            { "day": 11, "chat": [
                { "name": drifter, "text": "All right. Let's work on negotiating some kind of peace, here..." },
                { "name": drifter, "text": "I need to talk to Lizzie." },
                { "name": drifter, "text": "I don't think Lettie would appreciate if I had to sacrifice an animal..." },
                { "name": flare, "text": "when This Demon calls... We will always answer..." },
                { "name": flare, "text": "what do You need from Us, Sweet One?" },
                { "name": drifter, "text": "Flare is worried that once they let you in, you're going to consume their consciousness. They'll cease to be \"them.\"" },
                { "name": flare, "text": "what is so special about being Them?" },
                { "name": flare, "text": "They are an empty husk, a shell of a porcelain painted doll without Us" },
                { "name": flare, "text": "We seek to fill Them up with Song. With Greatness. With that which They have sought Their entire lives" },
                { "name": flare, "text": "They chase the stars, and we consume Them" },
                { "name": flare, "text": "and in joining with us, They will know what it is to be That which They Seek" },
                { "name": drifter, "text": "So... you *do* plan to consume their consciousness?" },
                { "name": flare, "text": "y...es?" },
                { "name": flare, "text": "We. Plan. To. Share? Their? Mind?" },
                { "name": flare, "text": "Is that. Better?" },
                { "name": flare, "text": "We are not very good at being Small" },
                { "name": flare, "text": "it is why We have not spoken to this Demon very often" },
                { "name": drifter, "text": "When you say \"share\" though, do you mean... \"share\" like you tried to \"share\" Eleanor?" },
                { "name": flare, "text": "Yes! Precisely like that. She is such a Lovely One. We Love Her, So Very Much..." },
                { "name": flare, "text": "Why couldn't We have been Born to Her..." },
                { "name": flare, "text": "She would have Embraced Us..." },
                { "name": drifter, "text": "What's \"sharing\" to you, looks like \"destruction\" to us. You have to try to understand that. I know it's hard to \"be small\" but try. Remember what happened to Eleanor? And Lettie?" },
                { "name": flare, "text": "We saw it a million times over, and then a half a million again in salvation..." },
                { "name": flare, "text": "and again, and again, and again..." },
                { "name": flare, "text": "This Demon speaks sense...", "gold": true },
                { "name": flare, "text": "We will... consider Their words..." },
            ]},
            { "day": 12, "chat": [
                { "name": flare, "text": "i don't know why this shit scares me so much" },
                { "name": flare, "text": "it's not like i'm not used to this kind of nonsense already, if... not to this extent" },
                { "name": drifter, "text": "What do you mean?" },
                { "name": flare, "text": "sorry if i'm a bit melancholy. i woke up this morning feeling a way i haven't felt in a while" },
                { "name": flare, "text": "i don't know if it's the grief of the band's deaths or... this whole issue with *her* or what..." },
                { "name": drifter, "text": "I think you have a right to be a bit messed up right now." },
                { "name": flare, "text": "i suppose. but who doesn't?" },
                { "name": flare, "text": "although i suppose most of the others aren't contending with a soul-eating infested horror yammering at them at all hours" },
                { "name": flare, "text": "when i woke up today, i felt that same... dread i haven't felt since i was a youth" },
                { "name": flare, "text": "not the kind of \"oh, great, i'm going to die today\" kind of dread that she brings" },
                { "name": flare, "text": "or even the kind of shit you're used to dealing with on a daily basis. so it sounds a little trite to even whine about" },
                { "name": flare, "text": "but... i don't even know if this'll resonate with you..." },
                { "name": flare, "text": "but sometimes i wake up and i just don't know who the world expects me to be anymore..." },
                { "name": flare, "text": "whatever i am isn't good enough. whatever i am can't check the boxes" },
                { "name": flare, "text": "constantly fed images and standards of what i'm *supposed* to be, every day of my life, everywhere i go" },
                { "name": flare, "text": "the other day i saw this gym bunny walk down the street" },
                { "name": flare, "text": "absolute perfect specimen in impeccable clothes and a tight vest. you could have bounced a golden groat off that ass and gotten back two silvers and a bronzie" },
                { "name": flare, "text": "every inch of them dripping in class. status. confidence. money. their wristwatch probably cost more than what i'd make in a year" },
                { "name": flare, "text": "sol above i wanted them so badly. wanted to BE them so badly..." },
                { "name": flare, "text": "that's what i mean" },
                { "name": flare, "text": "look like this\" \"act like this\" \"feel like this\" \"BE THIS\" or you are WORTHLESS" },
                { "name": flare, "text": "trying to be what they want feels so wrong. and even if it didn’t? it'd be pointless... i know i'll fail... but not trying? ... lua, the loneliness feels like a crushing weight that makes it so it's hard to get out of bed some days" },
                { "name": flare, "text": "sorry..." },
                { "name": flare, "text": "this is probably all nonsense to you" },
                { "name": flare, "text": "i mean, look at us - look at *me,* darling - we couldn't be more different..." },
                { "name": drifter, "text": "No. It makes perfect sense to me. Trust me." },
                { "name": flare, "text": "maybe i make more sense to you than i thought, then", "gold": true },
                { "name": drifter, "text": "You have a new family now, in the other protoframes here. You have a place where you can be who you want to be." },
                { "name": drifter, "text": "You don't have to feel lonely anymore." },
                { "name": flare, "text": "that's a real sweet thought, but... family isn't the same as feeling like you belong in your own *self*" },
                { "name": flare, "text": "not to say that i haven't come around to appreciate this pack of walking science projects gone wrong" },
                { "name": drifter, "text": "Have you considered that... maybe that's what Lizzie is trying to do? To help you feel like you belong?" },
                { "name": drifter, "text": "Trying to \"consume\" your consciousness so you don't feel lonely anymore." },
                { "name": drifter, "text": "Making you part of one cosmic whole." },
                { "name": flare, "text": "i..." },
                { "name": flare, "text": "is that what i've really wanted this entire time?" },
                { "name": flare, "text": "to be a part of the stars?" },
                { "name": flare, "text": "i used to think all musicians wanted to die at the peak of their fame before they had a chance to burn out" },
                { "name": flare, "text": "thought that was my destiny in some weird way. shit, was i wrong." },
                { "name": flare, "text": "but... i think i've always yearned to be a part of something bigger, and i've certainly always felt like i didn't quite belong. you're telling me that's what she's tapping into?" },
                { "name": drifter, "text": "She's part you. She can feel that pain. That yearning. I think she's trying to *fix it.*" },
                { "name": flare, "text": "i... don't know how to feel about that, except... overwhelmed" },
                { "name": flare, "text": "i'm going to go jot some lyrics down, and... consider what you've just said...", "gold": true },
            ]},
            { "day": 13, "chat": [
                { "name": flare, "text": "helloooooooo, Our Sweetest Demon..." },
                { "name": drifter, "text": "Hi, Lizzie." },
                { "name": drifter, "text": "I think I understand what you've been trying to do this whole time." },
                { "name": drifter, "text": "You've been trying, in your own screwed up Infested way, to make Flare feel less lonely, haven't you?" },
                { "name": flare, "text": "Their soul cries out for a sense of Wholeness" },
                { "name": flare, "text": "For a Sense of Belonging..." },
                { "name": flare, "text": "We love Them more than We can put into words" },
                { "name": flare, "text": "Our whole Being sings for Them like the ballads They write" },
                { "name": flare, "text": "We never meant to scare Them... only to heal that which hurts Them..." },
                { "name": drifter, "text": "I believe you, and it was very kind. But I know how you can really help Flare." },
                { "name": flare, "text": "how would You have Us serve?" },
                { "name": drifter, "text": "Music is their life. And you're a guitar. Maybe that's the way in - show them the kind of music you two can make together." },
                { "name": flare, "text": "mmmmmm this Demon is clever..." },
                { "name": flare, "text": "clever and wise..." },
                { "name": flare, "text": "YES. We will show Them how Our songs together could make even The Smiling One wonder after Their emptiness", "gold": true },
                { "name": flare, "text": "come to Us tomorrow, let Us All Speak as One" },
            ]},
            { "day": 14, "chat": [
                { "name": drifter, "text": "Hey, Flare. You there?" },
                { "name": flare, "text": "hey. woke up with the weirdest headache and a helluva song idea" },
                { "name": flare, "text": "get the feeling that wasn't a coincidence" },
                { "name": drifter, "text": "I think I might have made a breakthrough, but I need you to trust me." },
                { "name": flare, "text": "trust you... how, exactly...?" },
                { "name": drifter, "text": "I want you to share control with Lizzie, just for a few minutes, so we can all talk at once." },
                { "name": flare, "text": "are you, in the words of our wise new friend, *fking nuts?!?!*" },
                { "name": flare, "text": "the moment i let her in when i'm in control, she'll never give it up again!!!" },
                { "name": flare, "text": "what you're asking me to do..." },
                { "name": flare, "text": "but it's like what you said, isn't it?" },
                { "name": drifter, "text": "Yes. ... Exactly." },
                { "name": flare, "text": "she hears my loneliness and is trying to fix it the only way she can" },
                { "name": flare, "text": "not understanding how horrifying it is for the rest of us" },
                { "name": flare, "text": "what makes you so certain she isn't going to just... take over and never leave?" },
                { "name": drifter, "text": "That's the thing about trust... sometimes you just have to shut your eyes and jump." },
                { "name": flare, "text": "guess you're right", "gold": true },
                { "name": flare, "text": "screw it... what do i have left to lose" },
                { "name": flare, "text": "what value is there in the self, anyway?" },
                { "name": flare, "text": "all right... i hope you know what you're doing, drifter" },
                { "name": flare, "text": "" },
                { "name": flare, "text": "" },
                { "name": flare, "text": "" },
                { "name": flare, "text": "NNNGhhhhHh oohohhHHh Hellooo Sweet Demons..." },
                { "name": flare, "text": "This Tingles...heheheheeee" },
                { "name": flare, "text": "sol this is bizarre... i don't like this... make this quick, please, drifter..." },
                { "name": flare, "text": "Ooh don't be so frightened, Delicious One. We will not hurt You. We have come in kindness" },
                { "name": drifter, "text": "Flare. You miss your band." },
                { "name": flare, "text": "of course i do. they were murdered. they were my best friends. my whole purpose in life" },
                { "name": flare, "text": "how would you feel if the hex were taken away from you, after all you've been through now?" },
                { "name": flare, "text": "i feel like my heart's been ripped out of my chest and a gaping black hole was left in its place" },
                { "name": drifter, "text": "But there is another way that Lizzie can help you feel whole again. Right, Lizzie?" },
                { "name": flare, "text": "YEsss.... if They are willing to listen..." },
                { "name": flare, "text": "why do you think i'm letting this happen?" },
                { "name": flare, "text": "it's bad enough you're in the guitar, i hate it when you crawl inside my head like this, too" },
                { "name": flare, "text": "i'm listening. so... talk" },
                { "name": drifter, "text": "The answer is right in front of you. Look at what she is." },
                { "name": drifter, "text": "She's *your music,* isn't she?" },
                { "name": drifter, "text": "Viktor took your friends away. Took your voice away. Took your only ability to express yourself and smashed it all to pieces." },
                { "name": drifter, "text": "But you're still getting on that stage with her, again and again. Fighting Viktor, refusing to stop trying to get your message out there." },
                { "name": drifter, "text": "And you're doing it with *her in your hands." },
                { "name": drifter, "text": "Lizzie. You don't need to consume them. Flare. You don't need to fight her." },
                { "name": drifter, "text": "Draw the lines between yourselves wherever you need to." },
                { "name": drifter, "text": "But together, through the music you make, you're one whole." },
                { "name": flare, "text": "i... won't lie... being on stage with her, feeling the highs we can reach... it's a kind of peace that scares me..." },
                { "name": flare, "text": "do not be afraid, Dear One... We are a weapon, We are a cradle. We are your lover. We are your death. We are your life. We are whatever You need us to be..." },
                { "name": flare, "text": "use Us... wield Us..." },
                { "name": flare, "text": "all We ask... is that You accept Us..." },
                { "name": flare, "text": "make Us sing" },
                { "name": flare, "text": "how do i know you won't turn on me? how do i know the moment i let my guard down you won't... just snap" },
                { "name": flare, "text": "to Love is to place ones Life in their hands..." },
                { "name": flare, "text": "We love You, Beautiful One..." },
                { "name": flare, "text": "let Us prove Our devotion..." },
                { "name": flare, "text": "i..." },
                { "name": drifter, "text": "Listen to your instincts, Flare. What's your heart telling you?" },
                { "name": flare, "text": "that i can't keep going like i was. that i've been trying to hold back the tide with a teacup" },
                { "name": flare, "text": "and right now, all i can feel... is her. she's in my head, in my heart, and... and i feel..." },
                { "name": flare, "text": "i feel the music we make when we're on that stage together" },
                { "name": flare, "text": "i'm sitting here sobbing..." },
                { "name": flare, "text": "and i don't know whose tears they are" },
                { "name": flare, "text": "They are Ours, Together, Lover..." },
                { "name": flare, "text": "yeah... they are, aren't they...?" },
                { "name": flare, "text": "hey, lizzie?" },
                { "name": flare, "text": "yes, Beautiful One?" },
                { "name": flare, "text": "i'm so sorry for shutting you out... i was just... so scared of facing what i'd -" },
                { "name": flare, "text": "what we'd become..." },
                { "name": flare, "text": "but now that i see it, feel it, i... was screaming at shadows..." },
                { "name": flare, "text": "the Shadows hold Dangers that are Real, Lover. You were right to be afraid" },
                { "name": flare, "text": "i... i want to climb onto that stage and scream this out into the world" },
                { "name": flare, "text": "Yeess..." },
                { "name": flare, "text": "let Us make the heavens weep Our tears", "gold": true },
            ]},
            { "day": 15, "chat": [
                { "name": flare, "text": "the music's been flowing again" },
                { "name": flare, "text": "it's like... it just won't stop now. it's keeping me up all hours" },
                { "name": drifter, "text": "Is this a good or a bad thing?" },
                { "name": flare, "text": "it's absolutely wonderfull!" },
                { "name": flare, "text": "i haven't felt the itch since... well..." },
                { "name": flare, "text": "since viktor killed my friends" },
                { "name": drifter, "text": "What's the song about?" },
                { "name": flare, "text": "i don’t know yet, honestly... i won't until i see it all together" },
                { "name": flare, "text": "besides, half the lyrics aren't even mine to write" },
                { "name": flare, "text": "she's been helping. she brings a certain... depth to them, i'll admit" },
                { "name": flare, "text": "goes a bit more death metal than i usually vibe with but hey, to each their own haha" },
                { "name": drifter, "text": "I'd love to see it when it's done. :)" },
                { "name": flare, "text": "of course" },
                { "name": flare, "text": "i never liked to show my lyrics to people early, anyway. especially joey" },
                { "name": flare, "text": "always in good fun, though. or at least, i liked to pretend it was" },
                { "name": flare, "text": "i think he was always just a bit salty that he never got to play lead guitar. wasn’t my fault he was so shit at playing the solos" },
                { "name": flare, "text": "does it really ever get any better? the grief over the ones you lose?" },
                { "name": drifter, "text": "No. It never gets any easier. You just adapt to carrying the weight." },
                { "name": flare, "text": "suspected that was the case. thanks for the honesty" },
                { "name": flare, "text": "we all knew we were in danger when we came here. we all said it was worth the risk" },
                { "name": flare, "text": "but sometimes i can't help but wonder..." },
                { "name": flare, "text": "if we shouldn't have just stayed home. stayed silent. if we had, they'd all still be alive" },
                { "name": drifter, "text": "You'll drive yourself crazy if you wonder \"what if\" for the rest of eternity. Don't let the guilt get to you." },
                { "name": drifter, "text": "Viktor is to blame. Not you. Not them." },
                { "name": flare, "text": "yeah. you're right. thanks, friend", "gold": true },
                { "name": flare, "text": "hm. that gives me some more lyric ideas. brb" },
            ]},
            { "day": 16, "chat": [
                { "name": flare, "text": "Deeemooon oh Deeeemoonnn!! We require Your input most hastily" },
                { "name": drifter, "text": "How can I help?" },
                { "name": flare, "text": "We are... trying to help Our Lover compose music, but We are not sure if We are any good at this..." },
                { "name": flare, "text": "would You be willing to assist Us? with this... act of... Song Lyrics...?" },
                { "name": drifter, "text": "The least I can do for you." },
                { "name": flare, "text": "well. here is Our contribution so far..." },
                { "name": flare, "text": "Whispers call from the great beyond, <br/>A song of silence, cold and strong. <br/>I reach for hands that do not exist, <br/>Yet pull me into death's abyss." },
                { "name": drifter, "text": "Brilliant. No notes." },
                { "name": flare, "text": ">3", "gold": true },
                { "name": flare, "text": "This Demon pleases us with its praise... We shall continue in this endeavor!" },
            ]},
            { "day": 17, "chat": [
                { "name": flare, "text": "hey, drifter" },
                { "name": flare, "text": "i don’t know how to describe it, it feels like my blood is electric" },
                { "name": flare, "text": "i haven't been this inspired since i first got the band together" },
                { "name": flare, "text": "i hope i can do them proud, wherever they are now" },
                { "name": flare, "text": "i didn't know how i was going to go forward without them, until now" },
                { "name": flare, "text": "astrin used to give me such shit whenever i wouldn't want to get out of bed" },
                { "name": flare, "text": "they were such a good friend. never let me wallow in my moods, y'know?" },
                { "name": flare, "text": "even when i insisted that's all i ever wanted to do" },
                { "name": flare, "text": "i wish that shitbird understood the kind of beautiful people he took out of this world..." },
                { "name": flare, "text": "but that's exactly *why* we carry on in their absence" },
                { "name": flare, "text": "and with lizzie... and because of you... i think i have the strength to do it" },
                { "name": flare, "text": "I wake up and the world feels gray, <br/>No golden light to start my day. <br/>I hear your voice, but it's just a dream, <br/>Like a memory fading in the beam." },
                { "name": flare, "text": "song's getting there" },
                { "name": flare, "text": "almost ready" },
                { "name": drifter, "text": "I think it's wonderful." },
                { "name": flare, "text": "thanks" },
                { "name": flare, "text": "i got amir to make lizzie one of his weird... ice cream sundae creations yesterday" },
                { "name": flare, "text": "it was a color that does not exist in nature. i think it was more gummy bear than actual ice cream" },
                { "name": flare, "text": "had all these... chocolate cookie topping things all over it, and... fried sprinkle bursts? i don't know" },
                { "name": flare, "text": "never thought i'd hear a guitar purr" },
                { "name": flare, "text": "she was just... so... happy" },
                { "name": flare, "text": "and i didn't even realize for a solid two minutes that... i was smiling, ear to ear" },
                { "name": flare, "text": "anyway... not really sure where i was going with that, except to just say... thanks" },
                { "name": flare, "text": "ttys" },
            ]},
            { "day": 18, "chat": [
                { "name": flare, "text": "DEeeeemoonnn!! Ooohhh DEEEMOONNNN!!! We have a surprise for You :D" },
                { "name": flare, "text": "sorry, i meant to warn you. she's just really excited today" },
                { "name": drifter, "text": "What has her all amped up today?" },
                { "name": flare, "text": "the song is done. well, the lyrics are done, anyway" },
                { "name": flare, "text": "want to hear them?" },
                { "name": drifter, "text": "I would love to!" },
                { "name": flare, "text": "here goes" },
                { "name": flare, "text": "I saw when Sol cracked open wide <br/>Spilled like honey, gold inside <br/>A million voices whisper sweet <br/>Through hollow halls and tangled dreams" },
                { "name": flare, "text": "Oh, am I the sinner or the saint today? <br/>Do I rise like the phoenix or just fade away?" },
                { "name": flare, "text": "You taste like fire, you sing like sin <br/>You pull me close and draw me in <br/>Oh, love me or leave me, just don't set me free <br/>I'd rather be yours than remember me" },
                { "name": flare, "text": "I feel you crawling under my skin <br/>A thousand hands, a voice within <br/>Oh, am I the keeper or the sacrifice? <br/>Am I your sickness or paradise?" },
                { "name": flare, "text": "Oh, am I the hero or the one to blame? <br/>Do I chase the light or get lost in the flames?" },
                { "name": flare, "text": "Golden halos and serpentine grins <br/>Every love song ends where it begins <br/>Will I rise? Will I fall? <br/>Will I rise? Will I fall?" },
                { "name": flare, "text": "so? what do you think? still needs a title and music like i said, but th-" },
                { "name": flare, "text": "YES, WHAT DO YOU THINK? IS THIS DEMON PROUD OF US? >:3" },
                { "name": drifter, "text": "Wow. That was amazing, I love it!!" },
                { "name": flare, "text": "she's purring again. got to find a way to work that into a music track" },
                { "name": drifter, "text": "So, what's the next step?" },
                { "name": flare, "text": "actually thought you might be able to help us with that" },
                { "name": flare, "text": "i was wondering, do you play guitar?" },
                { "name": drifter, "text": "I do. It's called a shawzin." },
                { "name": flare, "text": "lizzie and i were wondering if you'd like to help us compose the song" },
                { "name": flare, "text": "no rush. you can work on it in your own time" },
                { "name": flare, "text": "she'll be around to help you" },
                { "name": drifter, "text": "Are - are you offering to let me play Lizzie?" },
                { "name": flare, "text": "do You waaaaant to Play with Us, Precious Demooon?" },
                { "name": drifter, "text": "That sounds awesome, thank you!" },
                { "name": flare, "text": "awesome" },
                { "name": flare, "text": "and, hey. if it wasn't clear what this was, thanks. for everything. for helping me, and lizzie, and... for being a real friend" },
                { "name": flare, "text": "we'll be here for you whenever you need us, space traveler" },
                { "name": flare, "text": "wherever it might take Us ;)" },
            ]},
            { "day": 19, "chat": [
                { "name": drifter, "text": "What do you like to do for your birthday, Flare?" },
                { "name": flare, "text": "normally? drink myself silly and go out on the town with friends" },
                { "name": flare, "text": "but i guess now my home is a bar, so... let 'er rip, i suppose", "gold": true  },
            ]},
        ]
    };
    return {
        script: script
    }
})();
